version: '3.8'

# Standalone deployment without Traefik
# Use this when you want to run without reverse proxy
# Usage: ROWT_PORT=3000 docker-compose -f docker-compose.yml -f docker-compose.standalone.yml up -d

services:
  rowt-server:
    # Override: Expose port directly for standalone deployment
    ports:
      - "${ROWT_PORT:-3000}:3000"
    # Override: Remove all Traefik labels
    labels: []
    # Override: Use only the internal network (remove traefik network)
    networks:
      - rowt-network
